### ISSUE TITLE
[Question] - Spawns

### ISSUE THREAD

**Issue by newacc12** [otland/forgottenserver#2517]
The problem that I will describe **doesn't** reside in this repository. I just want to understand some parts of the code **in this repository** so I can come up with a solution for the sources that I am working on. To ask the questions I will use the codes that **are on this repository**. If I am not supposed to post this here, please delete the post.

The source that I am working on has a feature to spawn monsters even if a player is on the screen (like tibia global). However, if a player move the monster outside of its spawn zone (red in the screenshot) the server is spawning a new one even if the existing creature is still alive:

![image](https://user-images.githubusercontent.com/20234557/49602176-6e1d1d80-f94d-11e8-9fcd-a174de2763d1.png)

Upon investigation I found that this happens because the elseif on the cleanup method on the spawn.cpp file is "removing" the creature from its spawnZone if it is not there:

**(sources from this repository)**
```
void Spawn::cleanup()
{
	auto it = spawnedMap.begin();
	while (it != spawnedMap.end()) {
		uint32_t spawnId = it->first;
		Monster* monster = it->second;
		if (monster->isRemoved()) {
			if (spawnId != 0) {
				spawnMap[spawnId].lastSpawn = OTSYS_TIME();
			}

			monster->decrementReferenceCounter();
			it = spawnedMap.erase(it);
		} else if (!isInSpawnZone(monster->getPosition()) && spawnId != 0) {
			spawnedMap.insert(spawned_pair(0, monster));
			it = spawnedMap.erase(it);
		} else {
			++it;
		}
	}
}
```

If I remove this elseif, the spawn seems to be normal. However, I have no idea what that could cause. My questions are:

1 - What is the purpose of this elseif? 
2 - Would it be safe to remove it?
3 - Another solution would be to add a condition on the checkSpawn method to check if the monster is still alive before spawning a new one but I don't know if it is possible (how to get a reference to the monster inside that method) and also if it would have any side effects:

**(sources from this repository)**
```
void Spawn::checkSpawn()
{
	checkSpawnEvent = 0;

	cleanup();

	uint32_t spawnCount = 0;

	for (auto& it : spawnMap) {
		uint32_t spawnId = it.first;
		if (spawnedMap.find(spawnId) != spawnedMap.end()) {
			continue;
		}

		spawnBlock_t& sb = it.second;
		if (OTSYS_TIME() >= sb.lastSpawn + sb.interval) {
			if (findPlayer(sb.pos)) {
				sb.lastSpawn = OTSYS_TIME();
				continue;
			}

			spawnMonster(spawnId, sb.mType, sb.pos, sb.direction);
			if (++spawnCount >= static_cast<uint32_t>(g_config.getNumber(ConfigManager::RATE_SPAWN))) {
				break;
			}
		}
	}

	if (spawnedMap.size() < spawnMap.size()) {
		checkSpawnEvent = g_scheduler.addEvent(createSchedulerTask(getInterval(), std::bind(&Spawn::checkSpawn, this)));
	}
}
```

**Comment by infister** [comment]
Can a monster be NOT removed and dead in the same time? I guess `isRemoved() == true` means its dead.

What is the point of checking if a monster is in a spawn zone? If he is not, what is the point of removing him from spawn? Is this some workaround for lacking of a real anti-lure system?

Mind that inserting him in the spawnedMap with spawnId 0 is totally pointless, because checkSpawn will continue and insert a duplicate monster anyway. Fix for (probably) missing anti-luring system created another bug with duplicated monsters.

**Comment by Leo32onGIT** [comment]
I think this is solved by having an appropriately sized spawn radius.

If my understand is correct, monsters only double spawn when they walk outside of their spawn radius (chasing a monster, player etc)

https://github.com/otland/forgottenserver/blob/master/src/spawn.cpp#L265-L285

So that room in the screenshot should be completely covered in one spawn radius, with one black knight in it, [like this](https://otland.net/threads/bug-with-respaw-appears-2-3-demons-if-player-lure.266571/#post-2583252).

Close this PR?

**Comment by infister** [comment]
This is just a workaround.

**Comment by Codinablack** [comment]
Why was this closed? It was never fixed and yet it's marked as completed... why? The bug still persists, the code is unchanged and its still there causing issues for players who use too small of a spawn radius... literally the algorithm for determining when to clean a monster from a "spawned" list is broken... Please re-open this, and please don't close things that aren't resolved.
