### ISSUE TITLE
Stepping into firefield while having fire condition from soulfire does not inflict damage

### ISSUE THREAD

**Issue by djseban** [otland/forgottenserver#2651]
Hey there,

recently I stumbled across the bug with conditions. Steps to reproduce:
1. Get hurt by soulfire rune.
2. Get hurt by firebomb and try to walk on  fire fields

In this scenario player does not receive any damage from fields, and after a while player gets damage until he dies. Any ideas on how to fix it :)? Tested on newest rev of tfs 1.3.

I also found gif of this bug:
![69154412_2440797525966780_8664424821154643968_o](https://user-images.githubusercontent.com/6154527/63889235-e1d1ef80-c9e0-11e9-85d8-0251540f0d10.jpg)

**Comment by Ochmar** [comment]
I think soulfire should be it's own CONDITION, not the fire one.
Correct me if I am wrong.

**Comment by joseluis2g** [comment]
Can you explain us how it should be.

**Comment by TheSumm** [comment]
The main issue with magic fields is that all the damage is applied through a damage condition, even the initial stepin damage. Conditions are only replaced if the newly applied condition does more total damage. Soul fire generally does more damage than a simply fire field due to its long duration.
Thus, when the player is already affected by soulfire, the fire field condition will not be applied.
This behaviour is correct, however the player should still suffer the initial stepin damage.

**Comment by Zbizu** [comment]
afaik in rl the most recent condition takes priority only when it has more damage to deal than already happening one (giant spider poison > poison field > poison spider poison) so a function to check remaining damage would be needed to assign condition priority.

**Comment by TheSumm** [comment]
That behaviour is already in place: https://github.com/otland/forgottenserver/blob/master/src/condition.cpp#L1011

**Comment by Olrios** [comment]
Based on gif he published - TFS' soulfire and/or firefield is bugged.

In real Tibia when you have soulfire condition on you, and when you step on firefield you getting 20 fire damage (or 10 if firefield is small) and everytime you step on it (on firefield). 1/2 dmg applies for PVP of course.

Soulfire applies 10 dmg ticks every 9 second, amount of ticks increases with you level and magic level. Formula for amount of ticks is very simple:

For mages: AMOUNT OF TICKS = (LEVEL + MAGIC) / 3
For paladins: AMOUNT OF TICKS = (LEVEL + MAGIC) / 15
For knights: AMOUNT OF TICKS = (LEVEL + MAGIC) / 20

Becouse we are using Open Tibia for custom servers it will be better to move the formula to LUA. With condition loop.

When you have soulfire dot and it's going to hit you only 4 more times and if you step on firefield which applies 7x 10dmg (each tick every 9 sec) then your condition will be equal to 7x 10 dmg.

If you have condition from firefield for 7x 10dmg and you get hit by weak soulfire for 5x 10dmg then your condition will be 7x 10dmg.

Firefields and other fields (psn energy etc) are bugged in almost all OTS and they never were fixed.

**Comment by nekiro** [comment]
I just checked what @Olrios said.
Field conditions are infinite when you stay on them.
Code Snippet: https://github.com/otland/forgottenserver/blob/master/src/condition.cpp#L1106-L1107

Condition also continues after the field is gone.

Thought this: 

> If you staying of firefield and someone hits you with soulfire for 50x 10dmg then you getting hits for infinity or when firefield disappear then you getting 7x 10dmg or remaining soulfire Xtick for 10dmg. Always higher will be chosen.

Makes no sense, like if you stay on firefield and you got "stronger" condition from soulfire, why would it choose to execute fire field condition which is weaker? In my opinion it should be execute soulfire if it ends, then inflict fire condition from the field. Are you sure about that?

About energy fields, you can fix that by simply editing items.xml

So conditions in general are working like they should?

About the bug:
https://nekiro.s-ul.eu/KMdMY3SV
I cant reproduce it?

**Comment by Olrios** [comment]
Why no sense? If you staying of firefield which wont disappear then infinity is always higher then any other value. Infinity will be always "stronger". But what if soulfire will be very weak like 3x 10dmg? In this case again you didn't understood, becouse firefield again in this case - isn't weaker like you said. Also "soulfire condition" isn't executed after "firefield condition" ends becouse there are no two conditions but only one - fire condition. Also from code view its still just one. All what I wrote is how it works exactly in real Tibia. And in OTS conditions are not working like they should.

**Comment by EPuncker** [comment]
is this somewhat involved with #2540 issue too?

**Comment by nekiro** [comment]
@EPuncker its not, but actually I fixed that issue in my recent pr, gonna link this issue too, th
anks

**Comment by EPuncker** [comment]
> @EPuncker its not, but actually I fixed that issue in my recent pr, gonna link this issue too, thanks

just tested it and the bug is still there, having soul fire, fire field doing no damage

**Comment by waqmaz93** [comment]
confirm

> > @EPuncker its not, but actually I fixed that issue in my recent pr, gonna link this issue too, thanks
> 
> just tested it and the bug is still there, having soul fire, fire field doing no damage

confirm
